### ISSUE TITLE
Multiday event spanning over months

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events-legacy#14]
Currently we only considered multiday events for short term spans within the same month, but what if the span was longer such as in the case with this Jan 13 to May 11th event.

![A25F8E41-3166-45FB-94B1-23B89E38BA14](https://user-images.githubusercontent.com/239259/71420371-b3c88900-2629-11ea-8586-c7ca2315b541.png)

**Comment by edalzell** [comment]
this is a template issue, likely. Although we should consider the event creation portion for events like that as adding each day individually will be awkward.

**Comment by edalzell** [comment]
@adnankussair this is interesting as a "multi-day" event is meant to be consecutive days, but this event they have is actually a recurring event, every 2 weeks (which we don't support).

How would you want to display this? And should we attempt to add support for `every_x` recurrence?

**Comment by adnankussair** [comment]
@edalzell I see. I guess we need to support a single event spanning across multiple months and also add support for every_x recurrence as well.

**Comment by edalzell** [comment]
why both @adnankussair ? What's different about them?

**Comment by adnankussair** [comment]
The first issue (more of a templating one which will fix the current issue seen on Zaytuna site) is that when a multi-day event spans across multiple days from one month to another let's say from January 31st to February 2nd. The event listing in collection 5 and 6 should display like so:

![Screen Shot 2020-01-03 at 8 07 24 AM](https://user-images.githubusercontent.com/239259/71734158-1b3bc100-2e00-11ea-9a6d-9fc7b039d9d8.png)

The second (more of a plugin enhancement) is the recurring events every_x. This will eliminate the need for each day to be entered manually when it doesn't meet one of the current recurrence criteria. This would probably replace the currently Daily, Weekly, Monthly with a multi step recurrent selection such as:

Every <#> <Day/Month/Week/Year>

So then this opens up the next ask I see coming, exceptions to the recurrence rule. Nothing we need to worry about yet, but maybe something we should open up as a Future Enhancements Roadmap item.
