### ISSUE TITLE
Changing an event from Recurring back to none breaks

### ISSUE THREAD

**Issue by sebszocinski** [transformstudios/statamic-events-legacy#19]
It seems setting Recurrence Type to None saves `false` as a string:

```
multi_day: false
start_date: 2020-01-18
recurrence: 'false'
```

Should be:

```
multi_day: false
start_date: 2020-01-18
recurrence: false
```

**Comment by edalzell** [comment]
@sebszocinski I think this is fixed, can you confirm?

**Comment by sebszocinski** [comment]
Yep you fixed it [here](https://github.com/transformstudios/statamic-events/commit/29a73ba084157bc337bde09e61e47fb885282ab3)
