### ISSUE TITLE
Multiday events which started in the past don't appear in list using in tag

### ISSUE THREAD

**Issue by sebszocinski** [transformstudios/statamic-events-legacy#20]
If you have an event that has multi-days and the first date was in the past, the remaining dates (in the future) don't show. This was only tested using the `in` tag .

**Comment by edalzell** [comment]
@sebszocinski can you show me the data please?

**Comment by edalzell** [comment]
and show me the template code you are using

**Comment by edalzell** [comment]
Haven't heard back in a while, closing. Please re-open if you get this again.

**Comment by sebszocinski** [comment]
Bringing this up as we've come across it again. It seems if you have a multi-day event and a day in the past and a day today it doesn't show up using the `in` tag.

```
{{ events:in collection="events" next="90 days" }}
```

See here in the CMS:

![image](https://user-images.githubusercontent.com/5466694/97823682-9fedb900-1d09-11eb-95c2-e6ebe4d67919.png)

This test should show an event for today (2nd Nov) but it doesn't.

Let me know if you need anything else to test?

**Comment by edalzell** [comment]
@sebszocinski this bug is actually if the start time of the event today is in the past.

Would you expect an event that has already started, but not yet finished to show up here?

**Comment by edalzell** [comment]
Issue is that the start time of the event was midnight. If you make it 1 min after midnight this issues doesn't happen.

Fixing.
