### ISSUE TITLE
FR: Get calendar data via API - 2 hrs

### ISSUE THREAD

**Issue by KevinGrant12** [transformstudios/statamic-events-legacy#22]
- Possible async refresh

**Comment by edalzell** [comment]
What do you mean @KevinGrant12, can you give me an example of how you’d like to use it?

**Comment by KevinGrant12** [comment]
It would be awesome to be able to switch months without refreshing the page ( I.e. decouple the filtering from the url ). This way, if your calendar is further down the page, or you have other functionality tied to data ( views, modals ), the users current view will not be disrupted when viewing events.

**Comment by edalzell** [comment]
would an api work @KevinGrant12? For example, something like this `/!/Events/calendar?year=2020&month=february`?

**Comment by KevinGrant12** [comment]
Yes, I think that would do the trick!

**Comment by adnankussair** [comment]
@KevinGrant12 We'll be starting on this feature request next week. :)
