### ISSUE TITLE
Some of the events and calendar pages are showing up incorrectly

### ISSUE THREAD

**Issue by adnankussair** [transformstudios/statamic-events-legacy#25]
@edalzell Client (zaytuna.edu) noticed noticed that some of the events and calendar pages are showing up incorrectly:

1. February 1 is listed on a Sunday instead of Saturday:

![Screen Shot 2020-01-31 at 9 49 50 AM](https://user-images.githubusercontent.com/239259/73562037-1d00a080-440f-11ea-9699-ac918fbc26b9.png)

2. An event that is on March 8 is showing up on both Feb 8 and March 8
3. The events for Feb 14 and Feb 15 aren’t showing up at all.

**Comment by edalzell** [comment]
https://github.com/transformstudios/statamic-events/commit/22fdb40a4b1484b11099dbf8565f3e31a987bc0d
