### ISSUE TITLE
End Time on Upcoming Dates is always 'endOfDay' for SingleDayEvents

### ISSUE THREAD

**Issue by lachieh** [transformstudios/statamic-events-legacy#27]
Regardless of whether you select an end time or not, the `{{ end_time }}` always shows 11:59pm inside of the `{{ events:upcoming }}` tag.

Steps to reproduce:
1. Create a Single Day Event and select a start and end time.
2. Have a template that uses the `{{ end_time }}` value.
3. `{{ end_time }}` will display as 23:59:59

**Comment by sebszocinski** [comment]
This issue still occurs when using `{events:calendar}` or `{events:in}` loops and trying to access the `end_time`. It looks like `end_time` is being set in Events.php [here](https://github.com/transformstudios/statamic-events/blob/master/Events/Events.php#L39) and [here](https://github.com/transformstudios/statamic-events/blob/master/Events/Events.php#L62).
