### ISSUE TITLE
[FR] Add ability to filter using taxonomy, just as is possible on the `collection` tag

### ISSUE THREAD

**Issue by lachieh** [transformstudios/statamic-events-legacy#29]
It would be beneficial to be able to filter results by providing a taxonomy, in the same way this is possible on collections.

```twig
{{ events:upcoming taxonomy:event_categories="dining" }}
```

**Comment by edalzell** [comment]
@lachieh 1.5 hours

**Comment by edalzell** [comment]
@lachieh can you grab this version and see how it works for you?
