### ISSUE TITLE
[FR] Filter by featured status

### ISSUE THREAD

**Issue by lachieh** [transformstudios/statamic-events-legacy#32]
Show only 'featured' events where a boolean value on the event is `true`. I'm not sure if it is better to use a filter callback (like [collection custom filters](https://docs.statamic.com/addons/classes/filters)) or if it should be handled using conditions (like: `{{ events:upcoming featured:is="true" }}`).

**Comment by edalzell** [comment]
@lachieh 1.5 hours, hopefully less.

**Comment by lachieh** [comment]
Turns out we're not going to need this one. We can get the same functionality by adding an event to a taxonomy which is covered by #29.
