### ISSUE TITLE
Link to sample fieldset in docs not working.

### ISSUE THREAD

**Issue by beckysoll** [transformstudios/statamic-events-legacy#39]
it currently links to "https://statamic.com/event.yaml", i assume it should link to https://github.com/transformstudios/statamic-events/blob/master/event.yaml

**Comment by adnankussair** [comment]
Thanks @beckysoll we'll update the documentation.md to use absolute links so they show up correctly in the statamic  marketplace docs. Have a good one!

**Comment by adnankussair** [comment]
Confirmed as fixed in Statamic Marketplace with release of 1.5.1
