### ISSUE TITLE
FR: Ability to download single event as .ics file (iCal)

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-events-legacy#4]
**[Original report](https://bitbucket.org/trnsfm/statamic-plugin-events/issue/4) by Erin Dalzell (Bitbucket: [edalzell](https://bitbucket.org/edalzell), GitHub: [edalzell](https://github.com/edalzell)).**

----------------------------------------

**Comment by edalzell** [comment]
**Original comment by Erin Dalzell (Bitbucket: [edalzell](https://bitbucket.org/edalzell), GitHub: [edalzell](https://github.com/edalzell)).**

----------------------------------------

I have the [code already](https://statamic.com/marketplace/addons/ical)

**Comment by edalzell** [comment]
https://github.com/transformstudios/statamic-events/commit/868440bc83d6cefe5895e8378e91381949e1eb40

**Comment by edalzell** [comment]
@adnankussair I'm going to update Simple with this so you can see it, but we will likely want to visit the styling/organization. I'll walk you through it on our weekly meeting.

**Comment by adnankussair** [comment]
sounds great. Thanks Erin!
