### ISSUE TITLE
unsetting `limit` breaks pagination.

### ISSUE THREAD

**Issue by DavidStrada** [transformstudios/statamic-events-legacy#41]
I've found that the changed introduced in the latest version 
```
if ($limit = $this->getInt('limit')) {
     unset($this->parameters['limit']);        
}
``` 
breaks pagination, so items can not longer be paginated.

Introduced here https://github.com/transformstudios/statamic-events/commit/49eda05ec8bb97a5590f0c5fc2010608c064af78#diff-6ae417af955106d4e74b910848b98a4d0bdc8d12f1e013ca161541ada97faca4R181-R189

**Comment by edalzell** [comment]
fixed in 1.5.3
