### ISSUE TITLE
Can't show events for today only

### ISSUE THREAD

**Issue by sebszocinski** [transformstudios/statamic-events-legacy#43]
Using the `{{ events:in }}` with something like `next="1 day"` seems to show more than just todays events.

Examples tested:
`next="0 day"` = Loops Yesterday and Today (2 days)
`next="today"` = Loops Yesterday and Today (2 days)
`next="1 day"` = Loops Yesterday, Today and Tomorrow (3 days)
`next="1 days"` = Loops Yesterday, Today and Tomorrow (3 days)

Using latest version

**Comment by edalzell** [comment]
Added in 1.5.4
