### ISSUE TITLE
Calendar pagination skips over every other month starting on Feb 2020

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-events-legacy#5]
**[Original report](https://bitbucket.org/trnsfm/statamic-plugin-events/issue/5) by Adnan Kussair (Bitbucket: [adnankussair](https://bitbucket.org/adnankussair), GitHub: [adnankussair](https://github.com/adnankussair)).**

----------------------------------------

@{557058:3d3a775f-aaa3-44e4-af2d-ddd9f7f74e22} The calendar seems to pagination over February and jumps to March. If you click on March you get stuck on March\+ and can’t Paginate back to any previous months.  
See live example here: [https://zaytuna.edu/events?year=2020&month=January](https://zaytuna.edu/events?year=2020&month=January)

‌

**Comment by edalzell** [comment]
**Original comment by Erin Dalzell (Bitbucket: [edalzell](https://bitbucket.org/edalzell), GitHub: [edalzell](https://github.com/edalzell)).**

----------------------------------------

No one should be subject to February. Closing as Working As I Want

**Comment by edalzell** [comment]
**Original comment by Adnan Kussair (Bitbucket: [adnankussair](https://bitbucket.org/adnankussair), GitHub: [adnankussair](https://github.com/adnankussair)).**

----------------------------------------

hahha

**Comment by edalzell** [comment]
**Original comment by Erin Dalzell (Bitbucket: [edalzell](https://bitbucket.org/edalzell), GitHub: [edalzell](https://github.com/edalzell)).**

----------------------------------------

I can't reproduce this on simple nor zaytuna.

**Comment by adnankussair** [comment]
@edalzell Issue is occurring again in production. See here: https://zaytuna.edu/events?year=2020&month=January

Notice February is missing and month pagination skips to March.

**Comment by adnankussair** [comment]
@edalzell So it looks like the calendar is skipping over every other month starting February 2020.

Notice the following are missing on the zaytuna production site https://www.zaytuna.edu/events:
- February 2020
- April 2020
- June 2020
etc.

**Comment by edalzell** [comment]
@adnankussair Not an Event issue. Site helper tag in Simple was wrong. Fixed in Simple repo.
